import type { NextPage } from 'next'
import Head from 'next/head'
import { DeathCausesOverview } from '../components/DeathCauseOverview/DeathCausesOverview'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DeathCausesOverview />

      <footer className={styles.footer}>
        <a
          href="https://github.com/FarDust"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ by FarDust 🚀
        </a>
      </footer>
    </div>
  )
}

export default Home
